= C++ 实例对象生命周期

== 实例(objects)生命周期类型

. **自动(automatic)** 实例存放在栈(Stack)中，作用域结束，实例生命周期结束。
. **常量(static)** 实例存放在常量池中，程序结束，实例生命周期结束。
. **线程(thread)** 线程结束，实例生命周期结束。
. **动态(dynamic)** 实例存放在堆(Heap)中，调用内存分配函数，实例生命周期开始，调用内存释放函数，实例生命周期结束。

== Storage duration

All `objects` in a program have one of the following storage durations:

* **automatic** storage duration. The storage for the object is allocated at the beginning of the enclosing code block and deallocated at the end. All local objects have this storage duration, except those declared `static`, `extern` or `thread_local`.

* **static** storage duration. The storage for the object is allocated when the program begins and deallocated when the program ends. Only one instance of the object exists. All objects declared at namespace scope (including global namespace) have this storage duration, plus those declared with `static` or `extern`.

* **thread** storage duration. The storage for the object is allocated when the thread begins and deallocated when the thread ends. Each thread has its own instance of the object. Only objects declared `thread_local` have this storage duration. `thread_local` can appear together with static or extern to adjust linkage.

* **dynamic** storage duration. The storage for the object is allocated and deallocated per request by using dynamic memory allocation functions. __(since C++11)__

