= opengrok

1.install tomcat8.
....
sudo apt install tomcat8
....

2.modify tomcat default port,default is 8080.

[source,xml]
./etc/tomcat8/server.xml
....
<Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               URIEncoding="UTF-8"
               redirectPort="8443" />
....

3.install universal ctags,don't use `sudo apt install exuberant-ctags`,opengrok need universal-ctag,not exuberant-ctags.

....
git clone https://github.com/universal-ctags/ctags.git
./autogen.sh
./configure
make
sudo make install
....

4.install `opengrok` from `https://github.com/oracle/opengrok.git` .

''''
1.download binary gz file and unzip it.

2.exec follow shell command.

.... 
java -jar lib/opengrok.jar -s /home/ssnwt/src/opengrok/src -d /home/ssnwt/src/opengrok/data -U http://localhost:8080/source -W /home/ssnwt/src/opengrok/config.xml -H -v -P -S -G -c /usr/local/bin/ctags
....

`-s` :source root,you can place your source project at here.

`-d` :index data dir.

`-c` :universal-ctag bin dir.

`-v` :show progress.

`-P` :every dir in source root as an project.

`-U` :

`-H` :

`-S` :

`-G` :

[Note]
====
this command will spend a lot of time.
====

''''

5.open `http://localhost:8080/source` opengrok works.

== sampale

....
java -jar /home/ssnwt/src/opengrok/lib/opengrok.jar -s /home/ssnwt/src/opengrok/src -d /home/ssnwt/src/opengrok/data -U http://localhost:9090/source -W /home/ssnwt/src/opengrok/config.xml -T 16 --progress -S -H -P -G -c /usr/local/bin/ctags \
-r on \
-I *.java \
-I *.c \
-I *.cc \
-I *.h \
-I *.mk \
-I *.cpp \
-I *.aidl \
-I *.sh \
-i f:*.so \
-i f:*.gz \
-i f:*.o \
-i f:*.a \
-i f:*.zip \
-i f:*.html \
-i f:*.md \
-i f:*.ninga \
-i f:*.py \
-i f:*.js \
-i d:src/abi \
-i d:src/art \
-i d:src/compatibility \
-i d:src/cts \
-i d:src/dalvik \
-i d:src/developers \
-i d:src/development \
-i d:src/docs \
-i d:src/external \
-i d:src/libcore \
-i d:src/libnativehelper \
-i d:src/ndk \
-i d:src/pdk \
-i d:src/platform_testing \
-i d:src/prebuilts \
-i d:src/sdk \
-i d:src/test \
-i d:src/toolchain \
-i d:src/tools \
-i d:test \
-i d:tests \
-i d:abi \
-i d:art \
-i d:compatibility \
-i d:cts \
-i d:dalvik \
-i d:developers \
-i d:development \
-i d:docs \
-i d:external \
-i d:libcore \
-i d:libnativehelper \
-i d:ndk \
-i d:pdk \
-i d:platform_testing \
-i d:prebuilts \
-i d:sdk \
-i d:toolchain \
-i d:tools
....

