= remote usb device 

install usbip.
....
sudo apt install linux-tools-generic
....
after this,it may recommand you to install spcific version of usbip.


== Server

1.Load the USBPIP kernel driver.
....
sudo modprobe usbip_host
....

2.Start the USB/IP daemon.
....
sudo usbipd -D
....

3.List all the devices connected.
....
sudo usbip list -l
....

....
- busid 1-3 (2a7a:6a18)
   unknown vendor : unknown product (2a7a:6a18)

 - busid 1-7 (275d:0ba6)
   unknown vendor : unknown product (275d:0ba6)
....

4.Select the device you want to share and bind it with the following command.
....
sudo usbip bind -b <busid>

//eg:sudo usbip bind -b 1-3
//usbip: info: bind device on busid 1-3: complete
....

== Client

1.Mount the VHCI driver.
....
sudo modprobe vhci-hcd
....

2.List all devices available from the server.
....
sudo usbip list -r <ip>
....

3.Let's attach to the selected device.
....
sudo usbip attach -r <ip> -b <busid>
....

== Disconnect

In order to disconnect the devices you must firt detach from your client:

1. List all devices attached.
....
sudo usbip port

Imported USB devices
====================
libusbip: error: fopen
libusbip: error: read_record
Port 00: <Port in Use> at High Speed(480Mbps)
       Samsung Electronics Co., Ltd : unknown product (04e8:6862)
       3-1 -> unknown host, remote port and remote busid
           -> remote bus/dev 001/011
....

2.Detach the corresponding port.
....
sudo usbip detach -p 00
....

Then we just unbind the device from our server.

3.Unbind device on server side.
....
sudo usbip unbind -b <busid>
....
